# Generated by r6-generator-maven-plugin: do not edit by hand
#' This is the main entry point of the roogledocs generated R library.
#'
#' @description
#' R wrapper for Googledocs java library
#'
#' Version: 0.01
#'
#' Generated: 2022-03-29T00:57:28.046
#'
#' Contact: rob@terminological.co.uk
#' @import rJava
#' @export
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	#' @field .log a pointer to the java logging system
	.log = NULL,
	#' @field .fromJava a set of type conversion functions from Java to R
	.fromJava = NULL,
	#' @field .toJava a set of type conversion functions from R to Java
	.toJava = NULL,
	#' @field .reg the list of references to java objects created by this API 
	.reg = list(),
	RoogleDocs = NULL,

	#' @description
    #' change the java logging level
    #' @param logLevel A string such as "DEBUG", "INFO", "WARN"
    #' @return nothing
  	changeLogLevel = function(logLevel) {
  		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "changeLogLevel" , logLevel)
  		invisible(NULL)
    },
	
	#' @description
    #' change the java logging level using a log4j configuration file
    #' @param log4jproperties An absolute filepath to the log4j propertied file
    #' @return nothing
	reconfigureLog = function(log4jproperties) {
  		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "reconfigureLog" , log4jproperties)
  		invisible(NULL)
    },
	
	#' @description
    #' print java system messages to the R console and flush the message cache. This is generally called automatically,
    #' @return nothing
	printMessages = function() {
		cat(.jcall("uk/co/terminological/rjava/LogController", returnSig = "Ljava/lang/String;", method = "getSystemMessages"))
		invisible(NULL)
	},
	
	
 	#### constructor ----
 	#' @description
 	#' Create the R6 api library class. This is the entry point to all Java related classes and methods in this package.
    #' @param logLevel A string such as "DEBUG", "INFO", "WARN" (defaults to "INFO")
    #' @examples
    #' \dontrun{
    #' J = roogledocs::JavaApi$get();
	#' }
    #' @return nothing
 	initialize = function(logLevel = "INFO") {
 		if (!is.null(JavaApi$singleton)) stop("Startup the java api with JavaApi$get() rather than using this constructor directly")
 	
 		message("Initialising R wrapper for Googledocs java library")
 		message("Version: 0.01")
		message("Generated: 2022-03-29T00:57:28.046")
 	
		if (!.jniInitialized) 
	        .jinit(parameters=getOption("java.parameters"),silent = TRUE, force.init = FALSE)
		
		# add in all the jars that come with the library
	    classes <- system.file("java", package = "roogledocs")
	    if (nchar(classes)) {
	        .jaddClassPath(classes)
	        jars <- grep(".*\\.jar", list.files(classes, full.names = TRUE), TRUE, value = TRUE)
	        message(paste0("Adding to classpath: ",jars,collapse='\n'))
	        .jaddClassPath(jars)
	    }
 	
 		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "setupRConsole")
 		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "configureLog" , logLevel)
 		# TODO: this is the library build date code byut it requires testing
 		# buildDate = .jcall("uk/co/terminological/rjava/LogController", returnSig = "S", method = "getClassBuildTime")
    	self$.log = .jcall("org/slf4j/LoggerFactory", returnSig = "Lorg/slf4j/Logger;", method = "getLogger", "roogledocs");
    	.jcall(self$.log,returnSig = "V",method = "info","Initialised roogledocs");
		.jcall(self$.log,returnSig = "V",method = "debug","Version: 0.01");
		.jcall(self$.log,returnSig = "V",method = "debug","R package generated: 2022-03-29T00:57:28.046");
		# .jcall(self$.log,returnSig = "V",method = "debug",paste0("Java library compiled: ",buildDate));
		.jcall(self$.log,returnSig = "V",method = "debug","Contact: rob@terminological.co.uk");
		self$printMessages()
		# initialise type conversion functions
		
		self$.toJava = list(
			RNumericArray=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				if (!is.array(rObj)) stop('expected an array')
				tmpVec = as.vector(as.numeric(rObj))
				tmpDim = dim(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray',rJava::.jarray(tmpVec),rJava::.jarray(tmpDim)))
			},
			RDateVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RDateVector'))
				if (any(na.omit(rObj)<'0001-01-01')) message('dates smaller than 0001-01-01 will be converted to NA')
				tmp = as.character(rObj,format='%C%y-%m-%d')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDateVector',rJava::.jarray(tmp)))
			},
			RDate=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RDate'))
				if (length(rObj) > 1) stop('input too long')
			   if (rObj<'0001-01-01') message('dates smaller than 0001-01-01 will be converted to NA')
				tmp = as.character(rObj,format='%C%y-%m-%d')[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDate',tmp))
			},
			RCharacterVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector'))
				if (!is.character(rObj)) stop('expected a vector of characters')
				tmp = as.character(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector',rJava::.jarray(tmp)))
			},
			RoogleDocs=function(rObj) return(rObj$.jobj),
			RNumeric=function(rObj) {
				if (length(rObj) > 1) stop('input too long')
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumeric',tmp))
			},
			RFactor=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				tmpLabel = levels(rObj)[[tmp]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor',tmp, tmpLabel))
			},
			RLogical=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical'))
				if (length(rObj) > 1) stop('input too long')
				if (!is.logical(rObj)) stop('expected a logical')
				tmp = as.integer(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical',tmp))
			},
			RCharacter=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter'))
				tmp = as.character(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter',tmp))
			},
			RLogicalVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector'))
				if (!is.logical(rObj)) stop('expected a vector of logicals')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector',rJava::.jarray(tmp)))
			},
			RNull=function(rObj) {
				if (!is.null(rObj)) stop('input expected to be NULL')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNull'))
			},
			String=function(rObj) return(as.character(rObj)),
			void=function(rObj) stop('no input expected'),
			double=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java double')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.numeric(rObj)) stop('not an double')
			    return(as.numeric(rObj[[1]]))
			},
			RList=function(rObj) {
			   if (!is.list(rObj)) stop ('expecting a list ')
			   if (!is.null(names(rObj))) warning('not expecting list to be named')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RList')
				lapply(rObj, function(x) {
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Z',method='add',rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			},
			RNumericVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector',rJava::.jarray(tmp)))
			},
			int=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java int')
			    if (length(rObj) > 1) stop('input too long')
			    if (as.integer(rObj)[[1]]!=rObj[[1]]) stop('not an integer')
			    return(as.integer(rObj[[1]]))
			},
			boolean=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java boolean')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.logical(rObj)) stop('not a logical')
			    return(as.logical(rObj[[1]]))
			},
			RInteger=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				if (rObj[[1]]!=tmp) stop('cannot cast to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger',tmp))
			},
			RBoundDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RUntypedNaVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RUntypedNaVector'))
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNaVector',length(rObj)))
			},
			RUntypedNa=function(rObj) {
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNa'))
			},
			RFactorVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector'))
				if (!is.factor(rObj)) stop('expected a vector of factors')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector', rJava::.jarray(tmp), rJava::.jarray(levels(rObj))))
			},
			RIntegerVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector'))
				tmp = as.integer(rObj)
				if (any(rObj!=tmp,na.rm=TRUE)) stop('cannot coerce to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector',rJava::.jarray(tmp)))
			},
			RNamedList=function(rObj) {
				if (!is.list(rObj) | is.null(names(rObj))) stop ('expecting a named list')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RNamedList')
				lapply(names(rObj), function(name) {
					x = rObj[[name]]
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RObject;',method='put',name,rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			}		)
		
		self$.fromJava = list(
			RNumericArray=function(jObj) {
				tmpVec = as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive'))
				tmpDim = as.integer(rJava::.jcall(jObj,returnSig='[I',method='rDim'))
			   if (length(tmpDim)==2) return(matrix(tmpVec,tmpDim))
				return(array(tmpVec,tmpDim))
			},
			RDateVector=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RDate=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RCharacterVector=function(jObj) as.character(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive')),
			RoogleDocs=function(jObj) return(jObj),
			RNumeric=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='D',method='rPrimitive')),
			RFactor=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rLabel')),
			RLogical=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RCharacter=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive')),
			RLogicalVector=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RNull=function(jObj) return(NULL),
			String=function(jObj) return(as.character(jObj)),
			void=function(jObj) invisible(NULL),
			double=function(jObj) return(as.numeric(jObj)),
			RList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			},
			RNumericVector=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive')),
			int=function(jObj) return(as.integer(jObj)),
			boolean=function(jObj) return(as.logical(jObj)),
			RInteger=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RBoundDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RUntypedNaVector=function(jObj) rep(NA, rJava::.jcall(jObj,returnSig='I',method='size')),
			RUntypedNa=function(jObj) return(NA),
			RFactorVector=function(jObj) ordered(
				x = rJava::.jcall(jObj,returnSig='[I',method='rValues'),
				labels = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rLevels')
			),
			RIntegerVector=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RNamedList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			}		)
	
		# initialise java class constructors and static method definitions
		
		self$RoogleDocs = list(
			new = function(tokenDirectory=normalizePath('~/.roogledocs', mustWork = FALSE)) {
				# constructor
				# convert parameters to java
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				# invoke constructor method
				tmp_out = .jnew("org/github/terminological/roogledocs/RoogleDocs" , tmp_tokenDirectory); 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = RoogleDocs$new(
					self$.fromJava$RoogleDocs(tmp_out),
					self
				);
				self$printMessages()
				return(tmp_r6)
			}
	)
	}
))

JavaApi$singleton = NULL

JavaApi$get = function(logLevel = "INFO") {
	if (is.null(JavaApi$singleton)) {
		JavaApi$singleton = JavaApi$new(logLevel)
	}
	return(JavaApi$singleton)
}

