# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob@terminological.co.uk
# R wrapper for Googledocs java library
#' R6 Bindings for Java RoogleDocs
#'
#' @description
#' Programmatically substitute data into a google doc
#' 
#' This is a class of the roogledocs generated R library.
#' 
#' Version: 0.01
#' 
#' Generated: 2022-03-29T00:57:28.117
#'
#' @details
	#' Programmatically substitute data into a google doc
#' @export
RoogleDocs = R6::R6Class("RoogleDocs", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new RoogleDocs this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new RoogleDocs object.
	#' @examples
	#' J = roogledocs::JavaApi$get();
	#' instance = J$RoogleDocs$new(tokenDirectory=normalizePath('~/.roogledocs', mustWork = FALSE))
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' withDocument: 
	#' Select a document by its share url or id.
	#' @param shareUrlOrDocId the url from clicking a share button in google docs or an id from searchForDocuments() method - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	withDocument = function(shareUrlOrDocId) {
		# copy parameters
		tmp_shareUrlOrDocId = self$.api$.toJava$String(shareUrlOrDocId);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="withDocument" , tmp_shareUrlOrDocId); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' findOrCreateDocument: 
	#' Search for or create a document if it is missing.
	#' @param title a document title. If there is an exact match in google drive then that document will be used 
	#' otherwise a new one will be created. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	findOrCreateDocument = function(title) {
		# copy parameters
		tmp_title = self$.api$.toJava$String(title);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="findOrCreateDocument" , tmp_title); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' searchForDocuments: 
	#' no description
	#' @param titleMatch a string to be searched for as an approximate match. All results will be retrieved with document ids. - (java expects a String)
	#' @return RDataframe: 
	#' a dataframe containing id and name columns
	searchForDocuments = function(titleMatch) {
		# copy parameters
		tmp_titleMatch = self$.api$.toJava$String(titleMatch);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="searchForDocuments" , tmp_titleMatch); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' tagsDefined: 
	#' Finds tags defined in the current document
	#' @return RDataframe: 
	#' a dataframe containing tag and count columns
	tagsDefined = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="tagsDefined" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' updateTaggedText: 
	#' Subsititutes all occurrences of {{tag-name}} with the text parameter.
	#' @param tagName the tag name - (java expects a String)
	#' @param text the value to relace the tag with (e.g. a result from analysis) - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedText = function(tagName, text) {
		# copy parameters
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_text = self$.api$.toJava$String(text);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedText" , tmp_tagName, tmp_text); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' updateTaggedImage: 
	#' Subsitututes all occurrences of {{tag-name}} with an image from the local storage
	#' @param tagName the tag name - (java expects a String)
	#' @param absoluteFilePath a file path to an png imge file. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' 
	updateTaggedImage = function(tagName, absoluteFilePath) {
		# copy parameters
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedImage" , tmp_tagName, tmp_absoluteFilePath); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' revertTags: 
	#' remove all text and images inserted by roogledocs and returns the bare document. 
	#' This is needed if content is being moved
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	revertTags = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="revertTags" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	
	#' @description The output of toString() of this RoogleDocs
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this RoogleDocs
	#' @param object The R6 instance to test for equality to this RoogleDocs  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/roogledocs/RoogleDocs")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
