# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob@terminological.co.uk
# R wrapper for Googledocs java library
#' R6 Bindings for Java RoogleDocs
#'
#' @description
#' Programmatically substitute data into a google doc
#' 
#' This is a class of the roogledocs generated R library.
#' 
#' Version: 0.01
#' 
#' Generated: 2022-04-26T17:14:25.269
#'
#' @details
	#' Programmatically substitute data into a google doc
#' @export
RoogleDocs = R6::R6Class("RoogleDocs", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new RoogleDocs this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new RoogleDocs object.
	#' @examples
	#' J = roogledocs::JavaApi$get();
	#' instance = J$RoogleDocs$new(tokenDirectory=normalizePath('~/.roogledocs', mustWork = FALSE))
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' withDocument: 
	#' Select a document by its share url or id.
	#' @param shareUrlOrDocId the url from clicking a share button in google docs or an id from searchForDocuments() method - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	withDocument = function(shareUrlOrDocId) {
		# copy parameters
		tmp_shareUrlOrDocId = self$.api$.toJava$String(shareUrlOrDocId);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="withDocument" , tmp_shareUrlOrDocId); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' findOrCreateDocument: 
	#' Search for or create a document if it is missing.
	#' @param title a document title. If there is an exact match in google drive then that document will be used 
	#' otherwise a new one will be created. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	findOrCreateDocument = function(title) {
		# copy parameters
		tmp_title = self$.api$.toJava$String(title);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="findOrCreateDocument" , tmp_title); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' searchForDocuments: 
	#' no description
	#' @param titleMatch a string to be searched for as an approximate match. All results will be retrieved with document ids. - (java expects a String)
	#' @return RDataframe: 
	#' a dataframe containing id and name columns
	searchForDocuments = function(titleMatch) {
		# copy parameters
		tmp_titleMatch = self$.api$.toJava$String(titleMatch);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="searchForDocuments" , tmp_titleMatch); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' tagsDefined: 
	#' Finds tags defined in the current document
	#' @return RDataframe: 
	#' a dataframe containing tag and count columns
	tagsDefined = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="tagsDefined" ); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' updateTaggedText: 
	#' Substitutes all occurrences of {{tag-name}} with the text parameter.
	#' @param text the value to replace the tag with (e.g. a result from analysis) - (java expects a String)
	#' @param tagName the tag name - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedText = function(text, tagName) {
		# copy parameters
		tmp_text = self$.api$.toJava$String(text);
		tmp_tagName = self$.api$.toJava$String(tagName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedText" , tmp_text, tmp_tagName); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' updateTaggedImage: 
	#' Substitutes all occurrences of {{tag-name}} with an image from the local storage
	#' @param absoluteFilePath a file path to an png image file. - (java expects a String)
	#' @param tagName the tag name - (java expects a String)
	#' @param dpi the dots per inch of the image in the document (defaults to 300) - (defaulting to "300") - (java expects a double)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedImage = function(absoluteFilePath, tagName, dpi=300) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_dpi = self$.api$.toJava$double(dpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedImage" , tmp_absoluteFilePath, tmp_tagName, tmp_dpi); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' revertTags: 
	#' remove all text and images inserted by roogledocs and returns the bare document. 
	#' This is needed if content is being moved
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	revertTags = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="revertTags" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' updateTable: 
	#' no description
	#' @param longFormatTable A dataframe consisting of the table content and formatting indexed by row and column - (java expects a RDataframe)
	#' @param tableIndex what is the table index in the document? leave out for a new table at the end of the document. - (defaulting to "-1") - (java expects a int)
	#' @param colWidths A vector including the relative length of each column. This can be left out if longFormatTable comes from as.long_format_table - (defaulting to "attr(longFormatTable,'colWidths')") - (java expects a RNumericVector)
	#' @param tableWidthInches The final width of the table in inches (defaults to a size that fits in A4 page with margins) - (defaulting to "5.9") - (java expects a RNumeric)
	#' @return R6 RoogleDocs object: 
	#' 
	updateTable = function(longFormatTable, tableIndex=-1, colWidths=attr(longFormatTable,'colWidths'), tableWidthInches=5.9) {
		# copy parameters
		tmp_longFormatTable = self$.api$.toJava$RDataframe(longFormatTable);
		tmp_tableIndex = self$.api$.toJava$int(tableIndex);
		tmp_colWidths = self$.api$.toJava$RNumericVector(colWidths);
		tmp_tableWidthInches = self$.api$.toJava$RNumeric(tableWidthInches);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTable" , tmp_longFormatTable, tmp_tableIndex, tmp_colWidths, tmp_tableWidthInches); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	#' @description 
	#' updateFigure: 
	#' no description
	#' @param absoluteFilePath a file path to an png image file. - (java expects a String)
	#' @param figureIndex what is the figure index in the document (only counts inline images - not absolutely positioned ones)? leave out for a new image at the end of the document. - (defaulting to "-1") - (java expects a int)
	#' @param dpi the dots per inch of the image in the document (defaults to 300) - (defaulting to "300") - (java expects a double)
	#' @return R6 RoogleDocs object: 
	#' itself (a fluent method)
	updateFigure = function(absoluteFilePath, figureIndex=-1, dpi=300) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_figureIndex = self$.api$.toJava$int(figureIndex);
		tmp_dpi = self$.api$.toJava$double(dpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateFigure" , tmp_absoluteFilePath, tmp_figureIndex, tmp_dpi); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	
	#' @description The output of toString() of this RoogleDocs
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this RoogleDocs
	#' @param object The R6 instance to test for equality to this RoogleDocs  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/roogledocs/RoogleDocs")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
