# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob.challen@bristol.ac.uk
# Automated tests for roogledocs::RoogleDocs

# R6 RoogleDocs instance methods ----

# ├ enable() R6 method ----
# ├ disable() R6 method ----
# ├ getName() R6 method ----
# ├ tagsDefined() R6 method ----
# ├ updateTaggedText() R6 method ----
# ├ updateTaggedImage() R6 method ----
# ├ updateTaggedTable() R6 method ----
# ├ revertTags() R6 method ----
# ├ removeTags() R6 method ----
# ├ updateTable() R6 method ----
# ├ updateFigure() R6 method ----
# ├ saveAsPdf() R6 method ----
# ├ makeCopy() R6 method ----
# ├ delete() R6 method ----
# ├ uploadSupplementaryFiles() R6 method ----
# ├ appendText() R6 method ----
# ├ appendFormattedParagraph() R6 method ----
# ├ updateCitations() R6 method ----

# RoogleDocs static methods ----

# ├ reauth() package method ----
# ├ doc_by_id() package method ----
# ├ doc_by_name() package method ----
# ├ doc_from_template() package method ----
# ├ search_for_documents() package method ----
# ├ delete_document() package method ----
# ├ citation_styles() package method ----
