# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob.challen@bristol.ac.uk
# Automated tests for roogledocs::RoogleSlides

# R6 RoogleSlides instance methods ----

# ├ enable() R6 method ----
# ├ disable() R6 method ----
# ├ getName() R6 method ----
# ├ tagsDefined() R6 method ----
# ├ updateTaggedText() R6 method ----
# ├ updateTaggedImage() R6 method ----
# ├ updateTaggedTable() R6 method ----
# ├ removeTags() R6 method ----
# ├ saveAsPdf() R6 method ----
# ├ makeCopy() R6 method ----
# ├ delete() R6 method ----
# ├ uploadSupplementaryFiles() R6 method ----
# ├ appendFormattedSlide() R6 method ----
# ├ slideDimensions() R6 method ----
# ├ slideLayouts() R6 method ----
# ├ setDefaultLayout() R6 method ----
# ├ updateCitations() R6 method ----

# RoogleSlides static methods ----

# ├ slides_by_id() package method ----
# ├ slides_by_name() package method ----
# ├ slides_from_template() package method ----
# ├ search_for_slides() package method ----
# ├ delete_slides() package method ----
