# Generated by r6-generator-maven-plugin: do not edit by hand
#' This is the main entry point of the roogledocs generated R library.
#'
#' @description
#' R Wrapper For Googledocs Java Library
#'
#' Version: 0.1.0
#'
#' Generated: 2022-09-26T22:25:24.175057
#'
#' Contact: rob.challen@bristol.ac.uk
#' @import rJava 
#' @export
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	#' @field .log a pointer to the java logging system
	.log = NULL,
	#' @field .fromJava a set of type conversion functions from Java to R
	.fromJava = NULL,
	#' @field .toJava a set of type conversion functions from R to Java
	.toJava = NULL,
	#' @field .reg the list of references to java objects created by this API 
	.reg = list(),
	#' @field RoogleDocs the RoogleDocs class contructors and static methods
	RoogleDocs = NULL,

	#' @description
	#' change the java logging level
	#' @param logLevel A string such as "DEBUG", "INFO", "WARN"
	#' @return nothing
	changeLogLevel = function(logLevel) {
		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "changeLogLevel" , logLevel)
		invisible(NULL)
	},
	
	#' @description
	#' change the java logging level using a log4j configuration file
	#' @param log4jproperties An absolute filepath to the log4j propertied file
	#' @return nothing
	reconfigureLog = function(log4jproperties) {
		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "reconfigureLog" , log4jproperties)
		invisible(NULL)
	},
	
	#' @description
	#' print java system messages to the R console and flush the message cache. This is generally called automatically,
	#' @return nothing
	printMessages = function() {
		# check = FALSE here to stop exceptions being cleared from the stack.
		msg = .jcall("uk/co/terminological/rjava/LogController", returnSig = "Ljava/lang/String;", method = "getSystemMessages", check=FALSE)
		if (!is.null(msg) && trimws(msg) != "") message(trimws(msg))
		invisible(NULL)
	},
	
 	#### constructor ----
 	#' @description
 	#' Create the R6 api library class. This is the entry point to all Java related classes and methods in this package.
	#' @param logLevel One of "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE", "ALL". (defaults to "INFO") 
	#' @examples
	#' J = roogledocs::JavaApi$get();
	#' @return nothing
 	initialize = function(logLevel = "INFO") {
 		if (is.null(JavaApi$singleton)) stop("Startup the java api with JavaApi$get() rather than using this constructor directly")
 	
 	
 		.startJvm()
		
		# Java dependencies
		jars = .checkDependencies(quiet = TRUE)
		.jaddClassPath(jars)
		
		# configure logging
 		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "setupRConsole")
 		.jcall("uk/co/terminological/rjava/LogController", returnSig = "V", method = "configureLog" , logLevel)
 		# TODO: this is the library build date code but it requires testing
 		buildDate = .jcall("uk/co/terminological/rjava/LogController", returnSig = "S", method = "getClassBuildTime")
		self$.log = .jcall("org/slf4j/LoggerFactory", returnSig = "Lorg/slf4j/Logger;", method = "getLogger", "roogledocs");
		.jcall(self$.log,returnSig = "V",method = "debug", "Adding to classpath: ")
		for (jar in jars) {
		  .jcall(self$.log,returnSig = "V",method = "debug", jar)
		}
		.jcall(self$.log,returnSig = "V",method = "info","Initialised roogledocs");
		.jcall(self$.log,returnSig = "V",method = "debug","R package version: 0.1.0");
		.jcall(self$.log,returnSig = "V",method = "debug","R package generated: 2022-09-26T22:25:24.175260");
		.jcall(self$.log,returnSig = "V",method = "debug","Java library version: io.github.terminological:roogledocs:0.1.0");
		.jcall(self$.log,returnSig = "V",method = "debug",paste0("Java library compiled: ",buildDate));
		.jcall(self$.log,returnSig = "V",method = "debug","Contact: rob.challen@bristol.ac.uk");
		self$printMessages()
		
		# initialise type conversion functions
		
		self$.toJava = list(
			RNumericArray=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				if (!is.array(rObj)) stop('expected an array')
				tmpVec = as.vector(as.numeric(rObj))
				tmpDim = dim(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray',rJava::.jarray(tmpVec),rJava::.jarray(tmpDim)))
			},
			RDateVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RDateVector'))
				if (any(na.omit(rObj)<'0001-01-01')) message('dates smaller than 0001-01-01 will be converted to NA')
				tmp = as.character(rObj,format='%C%y-%m-%d')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDateVector',rJava::.jarray(tmp)))
			},
			RDate=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RDate'))
				if (length(rObj) > 1) stop('input too long')
			   if (rObj<'0001-01-01') message('dates smaller than 0001-01-01 will be converted to NA')
				tmp = as.character(rObj,format='%C%y-%m-%d')[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDate',tmp))
			},
			RCharacterVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector'))
				if (!is.character(rObj)) stop('expected a vector of characters')
				tmp = as.character(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector',rJava::.jarray(tmp)))
			},
			RoogleDocs=function(rObj) return(rObj$.jobj),
			RNumeric=function(rObj) {
				if (length(rObj) > 1) stop('input too long')
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumeric',tmp))
			},
			RFactor=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				tmpLabel = levels(rObj)[[tmp]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor',tmp, tmpLabel))
			},
			RLogical=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical'))
				if (length(rObj) > 1) stop('input too long')
				if (!is.logical(rObj)) stop('expected a logical')
				tmp = as.integer(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical',tmp))
			},
			RNull=function(rObj) {
				if (!is.null(rObj)) stop('input expected to be NULL')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNull'))
			},
			RLogicalVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector'))
				if (!is.logical(rObj)) stop('expected a vector of logicals')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector',rJava::.jarray(tmp)))
			},
			RCharacter=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter'))
				tmp = as.character(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter',tmp))
			},
			String=function(rObj) return(as.character(rObj)),
			void=function(rObj) stop('no input expected'),
			double=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java double')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.numeric(rObj)) stop('not an double')
			    return(as.numeric(rObj[[1]]))
			},
			RList=function(rObj) {
			   if (!is.list(rObj)) stop ('expecting a list ')
			   if (!is.null(names(rObj))) warning('not expecting list to be named')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RList')
				lapply(rObj, function(x) {
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Z',method='add',rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			},
			RNumericVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector',rJava::.jarray(tmp)))
			},
			int=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java int')
			    if (length(rObj) > 1) stop('input too long')
			    if (as.integer(rObj)[[1]]!=rObj[[1]]) stop('not an integer')
			    return(as.integer(rObj[[1]]))
			},
			boolean=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java boolean')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.logical(rObj)) stop('not a logical')
			    return(as.logical(rObj[[1]]))
			},
			RInteger=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				if (rObj[[1]]!=tmp) stop('cannot cast to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger',tmp))
			},
			RBoundDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RUntypedNaVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RUntypedNaVector'))
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNaVector',length(rObj)))
			},
			RUntypedNa=function(rObj) {
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNa'))
			},
			RFactorVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector'))
				if (!is.factor(rObj)) stop('expected a vector of factors')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector', rJava::.jarray(tmp), rJava::.jarray(levels(rObj))))
			},
			RIntegerVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector'))
				tmp = as.integer(rObj)
				if (any(rObj!=tmp,na.rm=TRUE)) stop('cannot coerce to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector',rJava::.jarray(tmp)))
			},
			RNamedList=function(rObj) {
				if (!is.list(rObj) | is.null(names(rObj))) stop ('expecting a named list')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RNamedList')
				lapply(names(rObj), function(name) {
					x = rObj[[name]]
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RObject;',method='put',name,rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			}		)
		
		self$.fromJava = list(
			RNumericArray=function(jObj) {
				tmpVec = as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive'))
				tmpDim = as.integer(rJava::.jcall(jObj,returnSig='[I',method='rDim'))
			   if (length(tmpDim)==2) return(matrix(tmpVec,tmpDim))
				return(array(tmpVec,tmpDim))
			},
			RDateVector=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RDate=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RCharacterVector=function(jObj) as.character(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive')),
			RoogleDocs=function(jObj) return(jObj),
			RNumeric=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='D',method='rPrimitive')),
			RFactor=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rLabel')),
			RLogical=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RNull=function(jObj) return(NULL),
			RLogicalVector=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RCharacter=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive')),
			String=function(jObj) return(as.character(jObj)),
			void=function(jObj) invisible(NULL),
			double=function(jObj) return(as.numeric(jObj)),
			RList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			},
			RNumericVector=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive')),
			int=function(jObj) return(as.integer(jObj)),
			boolean=function(jObj) return(as.logical(jObj)),
			RInteger=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RBoundDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RUntypedNaVector=function(jObj) rep(NA, rJava::.jcall(jObj,returnSig='I',method='size')),
			RUntypedNa=function(jObj) return(NA),
			RFactorVector=function(jObj) ordered(
				x = rJava::.jcall(jObj,returnSig='[I',method='rValues'),
				labels = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rLevels')
			),
			RIntegerVector=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RNamedList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			}		)
	
		# initialise java class constructors and static method definitions
		
		self$RoogleDocs = list(
			new = function(tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE)) {
				# constructor
				# convert parameters to java
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				tmp_disabled = self$.toJava$boolean(disabled);
				# invoke constructor method
				tmp_out = .jnew("org/github/terminological/roogledocs/RoogleDocs" , tmp_tokenDirectory, tmp_disabled, check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = RoogleDocs$new(
					self$.fromJava$RoogleDocs(tmp_out),
					self
				);
				return(tmp_r6)
			},
			docById = function(shareUrlOrDocId, tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE)) {
				# copy parameters
				tmp_shareUrlOrDocId = self$.toJava$String(shareUrlOrDocId);
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				tmp_disabled = self$.toJava$boolean(disabled);
				#execute static call
				tmp_out = .jcall("org/github/terminological/roogledocs/RoogleDocs", returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="docById" , tmp_shareUrlOrDocId, tmp_tokenDirectory, tmp_disabled, check=FALSE);
				self$printMessages()
				.jcheck() 
				# wrap return java object in R6 class 
				out = RoogleDocs$new(
					self$.fromJava$RoogleDocs(tmp_out),
					self
				);
				return(out)
			},
			docByName = function(title, tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE)) {
				# copy parameters
				tmp_title = self$.toJava$String(title);
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				tmp_disabled = self$.toJava$boolean(disabled);
				#execute static call
				tmp_out = .jcall("org/github/terminological/roogledocs/RoogleDocs", returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="docByName" , tmp_title, tmp_tokenDirectory, tmp_disabled, check=FALSE);
				self$printMessages()
				.jcheck() 
				# wrap return java object in R6 class 
				out = RoogleDocs$new(
					self$.fromJava$RoogleDocs(tmp_out),
					self
				);
				return(out)
			},
			docFromTemplate = function(title, templateUri, tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE)) {
				# copy parameters
				tmp_title = self$.toJava$String(title);
				tmp_templateUri = self$.toJava$String(templateUri);
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				tmp_disabled = self$.toJava$boolean(disabled);
				#execute static call
				tmp_out = .jcall("org/github/terminological/roogledocs/RoogleDocs", returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="docFromTemplate" , tmp_title, tmp_templateUri, tmp_tokenDirectory, tmp_disabled, check=FALSE);
				self$printMessages()
				.jcheck() 
				# wrap return java object in R6 class 
				out = RoogleDocs$new(
					self$.fromJava$RoogleDocs(tmp_out),
					self
				);
				return(out)
			},
			searchForDocuments = function(titleMatch, tokenDirectory=.tokenDirectory()) {
				# copy parameters
				tmp_titleMatch = self$.toJava$String(titleMatch);
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				#execute static call
				tmp_out = .jcall("org/github/terminological/roogledocs/RoogleDocs", returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="searchForDocuments" , tmp_titleMatch, tmp_tokenDirectory, check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert java object back to R
				out = self$.fromJava$RDataframe(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			deleteDocument = function(docName, areYouSure=utils::askYesNo(paste0('Are you sure you want to delete ',docName),FALSE), tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE)) {
				# copy parameters
				tmp_docName = self$.toJava$String(docName);
				tmp_areYouSure = self$.toJava$boolean(areYouSure);
				tmp_tokenDirectory = self$.toJava$String(tokenDirectory);
				tmp_disabled = self$.toJava$boolean(disabled);
				#execute static call
				tmp_out = .jcall("org/github/terminological/roogledocs/RoogleDocs", returnSig = "V", method="deleteDocument" , tmp_docName, tmp_areYouSure, tmp_tokenDirectory, tmp_disabled, check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert java object back to R
				out = self$.fromJava$void(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			}	)
	}
))

JavaApi$singleton = NULL

JavaApi$get = function(logLevel = "INFO") {
	if (is.null(JavaApi$singleton)) {
		# set to non-null so that R6 constructor will work
		JavaApi$singleton = FALSE 
		JavaApi$singleton = JavaApi$new(logLevel)
	}
	return(JavaApi$singleton)
}

JavaApi$rebuildDependencies = function( ... ) {
	.startJvm()
	jars = .checkDependencies(nocache=TRUE, quiet=FALSE)
	if (!all(file.exists(jars))) {
		warning("The library has been rebuilt but there is still some missing dependencies: Out of the following")
		warning(paste0(jars,collapse="\n"))
		warning("The missing dependencies are:")
		warning(paste0(jars[file.exists(jars)],collapse="\n"))
		warning("Please double check this is not an issue with your connections etc")
		warning("The output of roogledocs::JavaApi$rebuildDependencies(debug=TRUE) may help diagnose the problem")
	}
	
	return(jars)
}

JavaApi$installDependencies = function() {
	.startJvm()
	jars = .checkDependencies(nocache=FALSE, quiet=FALSE)
	.jaddClassPath(jars)
}

JavaApi$versionInformation = function() {
	out = list(
		package = "roogledocs",
		r_package_version = "0.1.0",
		r_package_generated = "2022-09-26T22:25:24.201984",
		java_library_version = "io.github.terminological:roogledocs:0.1.0",
		maintainer = "rob.challen@bristol.ac.uk"
	)
	# try and get complilation information if library is loaded
	try({
		out$java_library_compiled = .jcall("uk/co/terminological/rjava/LogController", returnSig = "S", method = "getClassBuildTime")
	}, silent=TRUE)
	return(out)
}

## package private utility functions for managing maven dependencies ----
# as this is generated code configuration is hard coded here
# i.e. these functions are specific for the configuration of this package.


.checkDependencies = function(nocache = FALSE, ...) {
	package_jar = .package_jars(package_name="roogledocs",types="thin-jar")
	package_jar = package_jar[startsWith(fs::path_file(package_jar),"roogledocs-0.1.0")]
	
	# Java dependencies
	# the main java library has been compiled but external dependencies must be resolved by maven
	# successful resolution of the classpath libraries depends on the runtime machine and requires
	# access to the internet at a minimum.
	maven_dependencies = .resolve_dependencies(artifact="io.github.terminological:roogledocs:0.1.0", nocache=nocache, path=package_jar, ...)
	jars = .package_jars(package_name="roogledocs",types="thin-jar")
	# all jars in R package and maven dependencies
	jars = unique(c(jars,maven_dependencies))
	
	# find the jars that come bundled with the library:
	# and add any that have been resolved and downloaded by maven:
	return(jars)
}


.startJvm = function() {
	.start_jvm(debug=FALSE)
}

