# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R wrapper for Googledocs java library
#' R6 Bindings for Java RoogleDocs
#'
#' @description
#' Programmatically substitute images, data and tables into a google doc. 
#' 
#' This is a class of the roogledocs generated R library.
#' 
#' Version: 0.1.0
#' 
#' Generated: 2022-05-19T09:47:25.637
#'
#' @details
	#' R library to perform limited interactions with google docs (and maybe one day slides)
	#' in R via the Java API library. The purpose being to support google docs as a
	#' platform for interactive development and documentation of data analysis in R for scientific
	#' publication, although it is not limited to this purpose. The workflow supported is a parallel documentation and analysis
	#' where a team of people are working collaboratively on documentation, whilst at the same time analysis
	#' is being performed and results updated repeatedly as a result of new data. In this environment updating
	#' numeric results, tabular data and figures in word documents manually becomes annoying. With roogledocs
	#' you can automate this a bit like a RMarkdown document, but with the added benefit that the content
	#' can be updated independently of the analysis, by the wider team.
#' @export
RoogleDocs = R6::R6Class("RoogleDocs", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new RoogleDocs this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new RoogleDocs object.
	#' @examples
	#' J = roogledocs::JavaApi$get();
	#' instance = J$RoogleDocs$new(tokenDirectory=normalizePath('~/.roogledocs', mustWork = FALSE), disabled=getOption('roogledocs.disabled',FALSE))
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' reauth: 
	#' Reauthenticate the service deleting the existing OAuth tokens. Generally this would only be needed if 
	#' application permission updates are needed in which case the directory can be manually deleted anyway,
	#' or if you want to switch google user without using a different tokenDirectory.
	#' @return R6 RoogleDocs object: 
	#' a fluent method
	reauth = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="reauth" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' enable: 
	#' Enables roogledocs. It is likely one of `withDocument()`, `findOrCreateDocument()` or `findOrCloneTemplate()` methods will be needed to specify the document.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	enable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="enable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' disable: 
	#' disables roogledocs temporarily only for this document. While disabled all calls to roogledocs will silently fail.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	disable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="disable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' withDocument: 
	#' Select a document by its share url or id.
	#' @param shareUrlOrDocId the url from clicking a share button in google docs or an id from searchForDocuments() method - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	withDocument = function(shareUrlOrDocId) {
		# copy parameters
		tmp_shareUrlOrDocId = self$.api$.toJava$String(shareUrlOrDocId);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="withDocument" , tmp_shareUrlOrDocId, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' findOrCreateDocument: 
	#' Search for or create a document if it is missing.
	#' @param title a document title. If there is an exact match in google drive then that document will be used 
	#' otherwise a new one will be created. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	findOrCreateDocument = function(title) {
		# copy parameters
		tmp_title = self$.api$.toJava$String(title);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="findOrCreateDocument" , tmp_title, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' findOrCloneTemplate: 
	#' Search for or create a document as a copy of a template document if it is missing.
	#' @param title a document title. If there is an exact match in google drive then that document will be used
	#' otherwise a new one will be created. - (java expects a String)
	#' @param templateUri the share link (or document id) of a template google document - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	findOrCloneTemplate = function(title, templateUri) {
		# copy parameters
		tmp_title = self$.api$.toJava$String(title);
		tmp_templateUri = self$.api$.toJava$String(templateUri);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="findOrCloneTemplate" , tmp_title, tmp_templateUri, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' searchForDocuments: 
	#' Search for documents with the given title
	#' @param titleMatch a string to be searched for as an approximate match. All results will be retrieved with document ids. - (java expects a String)
	#' @return RDataframe: 
	#' a dataframe containing id and name columns
	searchForDocuments = function(titleMatch) {
		# copy parameters
		tmp_titleMatch = self$.api$.toJava$String(titleMatch);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="searchForDocuments" , tmp_titleMatch, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' tagsDefined: 
	#' Finds tags defined in the current document
	#' @return RDataframe: 
	#' a dataframe containing tag and count columns
	tagsDefined = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="tagsDefined" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' updateTaggedText: 
	#' Substitutes all occurrences of {{tag-name}} with the text parameter.
	#' @param text the value to replace the tag with (e.g. a result from analysis) (cannot be empty) - (java expects a String)
	#' @param tagName the tag name - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedText = function(text, tagName) {
		# copy parameters
		tmp_text = self$.api$.toJava$String(text);
		tmp_tagName = self$.api$.toJava$String(tagName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedText" , tmp_text, tmp_tagName, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTaggedImage: 
	#' Substitutes all occurrences of {{tag-name}} with an image from the local storage. There are limited circumstances
	#' in which using this is a good idea. It will almost always be better to use `updateFigure()` to insert an image
	#' by index. If you choose to ignore this warning, beware combining this with `updateFigure()` as potentially the figure indexes will
	#' change dynamically. You have been warned.
	#' @param absoluteFilePath a file path to an png image file. - (java expects a String)
	#' @param tagName the tag name - (java expects a String)
	#' @param dpi the dots per inch of the image in the document (defaults to 300) - (defaulting to 300) - (java expects a double)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedImage = function(absoluteFilePath, tagName, dpi=300) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_dpi = self$.api$.toJava$double(dpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedImage" , tmp_absoluteFilePath, tmp_tagName, tmp_dpi, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' revertTags: 
	#' remove all tagged text and images inserted by roogledocs and returns the bare document. This does not affect figures and tables inserted by index (i.e. without tags) 
	#' This is needed if content is being moved around as cut and paste of tagged content unfortunately removes the internal named range of the tag.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	revertTags = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="revertTags" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTable: 
	#' Update or insert a formatted table into the document. The table and formatting are described in a dataframe the format of which is documented in the as.long_format_table() method.
	#' @param longFormatTable A dataframe consisting of the table content and formatting indexed by row and column. at a minimum this should have columns label,row,col, but may also include
	#' rowSpan,colSpan,fillColour, leftBorderWeight, rightBorderWeight, topBorderWeight, bottomBorderWeight, alignment (START,CENTER,END), valignment (TOP,MIDDLE,BOTTOM), fontName, fontFace, fontSize. - (java expects a RDataframe)
	#' @param tableIndex what is the table index in the document? This can be left out for a new table at the end of the document. - (defaulting to -1) - (java expects a int)
	#' @param colWidths A vector including the relative length of each column. This can be left out if longFormatTable comes from as.long_format_table - (defaulting to attr(longFormatTable,'colWidths')) - (java expects a RNumericVector)
	#' @param tableWidthInches The final width of the table in inches (defaults to a size that fits in A4 page with margins) - (defaulting to 6.2) - (java expects a RNumeric)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTable = function(longFormatTable, tableIndex=-1, colWidths=attr(longFormatTable,'colWidths'), tableWidthInches=6.2) {
		# copy parameters
		tmp_longFormatTable = self$.api$.toJava$RDataframe(longFormatTable);
		tmp_tableIndex = self$.api$.toJava$int(tableIndex);
		tmp_colWidths = self$.api$.toJava$RNumericVector(colWidths);
		tmp_tableWidthInches = self$.api$.toJava$RNumeric(tableWidthInches);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTable" , tmp_longFormatTable, tmp_tableIndex, tmp_colWidths, tmp_tableWidthInches, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateFigure: 
	#' Update or insert a figure in the document.
	#' @param absoluteFilePath a file path to an png image file (only png is supported at this point). - (java expects a String)
	#' @param figureIndex what is the figure index in the document? (This only counts inline images - and ignores absolutely positioned ones). leave out for a new image at the end of the document. - (defaulting to -1) - (java expects a int)
	#' @param dpi the dots per inch of the image in the document (defaults to 300). the final size of the image in the doc will be determined by the image file dimensions and the dpi. - (defaulting to 300) - (java expects a double)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateFigure = function(absoluteFilePath, figureIndex=-1, dpi=300) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_figureIndex = self$.api$.toJava$int(figureIndex);
		tmp_dpi = self$.api$.toJava$double(dpi);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateFigure" , tmp_absoluteFilePath, tmp_figureIndex, tmp_dpi, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' saveAsPdf: 
	#' Saves a snapshot of the current google doc as a pdf to a local drive. This is mainly intended for testing.
	#' @param absoluteFilePath - a file path to save the pdf. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	saveAsPdf = function(absoluteFilePath) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="saveAsPdf" , tmp_absoluteFilePath, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' deleteDocument: 
	#' Deletes a google document by name.
	#' @param docName - the name of a document to delete. must be an exact and unique match. - (java expects a String)
	#' @param areYouSure - a boolean check. - (defaulting to utils::askYesNo(paste0('Are you sure you want to delete ',docName),FALSE)) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	deleteDocument = function(docName, areYouSure=utils::askYesNo(paste0('Are you sure you want to delete ',docName),FALSE)) {
		# copy parameters
		tmp_docName = self$.api$.toJava$String(docName);
		tmp_areYouSure = self$.api$.toJava$boolean(areYouSure);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="deleteDocument" , tmp_docName, tmp_areYouSure, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' appendText: 
	#' Append text to the document with optional paragraph styling. If you run text blocks into each other without newlines the whole resulting paragraph will be styled. You 
	#' would normally not want this so it is up to you to end paragraphs with a new line character, before changing styles.
	#' @param text - a single string with the text to append which may include newlines - (java expects a RCharacter)
	#' @param style - one of NORMAL_TEXT, TITLE, SUBTITLE, HEADING_1, ... HEADING_6 - (defaulting to 'NORMAL_TEXT') - (java expects a RCharacter)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	appendText = function(text, style='NORMAL_TEXT') {
		# copy parameters
		tmp_text = self$.api$.toJava$RCharacter(text);
		tmp_style = self$.api$.toJava$RCharacter(style);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="appendText" , tmp_text, tmp_style, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' appendFormattedParagraph: 
	#' Append a new paragraph, with text from the 'label' column with optional formating in the other columns.
	#' @param formattedTextDf - a data frame containing the columns label, and optionally: link (as a URL), fontName, fontFace, fontSize. - (java expects a RDataframe)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	appendFormattedParagraph = function(formattedTextDf) {
		# copy parameters
		tmp_formattedTextDf = self$.api$.toJava$RDataframe(formattedTextDf);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="appendFormattedParagraph" , tmp_formattedTextDf, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	
	#' @description The output of toString() of this RoogleDocs
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this RoogleDocs
	#' @param object The R6 instance to test for equality to this RoogleDocs  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/roogledocs/RoogleDocs")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
