# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R Wrapper For Googledocs Java Library
#' R6 Bindings for Java RoogleDocs
#'
#' @description
#' Programmatically substitute images, data and tables into a google doc. 
#' 
#' This is a class of the roogledocs generated R library.
#' 
#' Version: 0.4.0
#' 
#' Generated: 2024-04-05T16:34:41.885564628
#'
#' @details
	#' R library to perform limited interactions with google docs (and maybe
	#'   one day slides)
	#'   in R via the Java API library. The purpose being to
	#'   support google docs as a
	#'   platform for interactive development and
	#'   documentation of data analysis in R for scientific
	#'   publication,
	#'   although it is not limited to this purpose. The workflow supported is
	#'   a parallel documentation and analysis
	#'   where a team of people are
	#'   working collaboratively on documentation, whilst at the same time
	#'   analysis
	#'   is being performed and results updated repeatedly as a result
	#'   of new data. In this environment updating
	#'   numeric results, tabular
	#'   data and figures in word documents manually becomes annoying. With
	#'   roogledocs
	#'   you can automate this a bit like a RMarkdown document, but
	#'   with the added benefit that the content
	#'   can be updated independently
	#'   of the analysis, by the wider team.
#' @export
RoogleDocs = R6::R6Class("RoogleDocs", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new RoogleDocs this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new RoogleDocs object.
	#' @examples
	#' \dontrun{
	#' J = roogledocs::JavaApi$get()
	#' # This constructor must be called via the JavaApi where an appropriate set of parameters must be provided.
	#' instance = J$RoogleDocs$new(tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE))
	#' }	
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' enable: 
	#' Enables roogledocs method calls for this document. 
	#'   
	#'   It is likely one
	#'   of `withDocument()`, `findOrCreateDocument()` or
	#'   `findOrCloneTemplate()` methods will be needed to specify the
	#'   document.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	enable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="enable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' disable: 
	#' Disables roogledocs temporarily for this document. 
	#'   
	#'   While disabled
	#'   all calls to roogledocs will silently abort.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	disable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="disable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' getName: 
	#' Return the name of the document
	#' @param suffix an additional suffix to add to the name - (defaulting to `''`) - (java expects a String)
	#' @return String: 
	#' 
	getName = function(suffix='') {
		# copy parameters
		tmp_suffix = self$.api$.toJava$String(suffix);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="getName" , tmp_suffix, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$String(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' tagsDefined: 
	#' List all tags
	#'   
	#'   Finds tags defined in the current document
	#' @return RDataframe: 
	#' a dataframe containing tag and count columns
	tagsDefined = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="tagsDefined" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' updateTaggedText: 
	#' Replace tags for text
	#'   
	#'   Substitutes all occurrences of {{tag-name}}
	#'   with the text parameter. If the tag name is not 
	#'   found in the document
	#'   it is inserted at the end in a section labelled "Unmatched tags:".
	#'   From there
	#'   it can be cut and pasted into the right place.
	#' @param text the value to replace the tag with (e.g. a result from analysis)
	#'   (cannot be empty) - (java expects a String)
	#' @param tagName the tag name - (defaulting to `deparse(substitute(text))`) - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedText = function(text, tagName=deparse(substitute(text))) {
		# copy parameters
		tmp_text = self$.api$.toJava$String(text);
		tmp_tagName = self$.api$.toJava$String(tagName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedText" , tmp_text, tmp_tagName, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTaggedImage: 
	#' Replace a tag with an image.
	#'   
	#'   Substitutes all occurrences of
	#'   {{tag-name}} with an image from the local storage. 
	#'   
	#'   The image is
	#'   uploaded to your google drive as a temporary file, and briefly made
	#'   publicly readable. From there it is inserted into the 
	#'   google doc, and
	#'   one completed the temporary file deleted from your google drive.
	#'   Insertion is
	#'   done using the dimensions of the existing image (if
	#'   present) or the PNG dimensions if not.
	#'   Creating the image with the
	#'   correct dimensions (and providing the dpi if not 300) is
	#'   important.
	#'   
	#'   If the tag is missing from the document the image
	#'   is
	#'   inserted at the end (and tagged). From there it can be cut and pasted
	#'   to the correct place.
	#' @param absoluteFilePath a file path to an png image file. - (java expects a String)
	#' @param tagName the tag name - (defaulting to
	#'   `deparse(substitute(absoluteFilePath))`) - (java expects a String)
	#' @param dpi the dots per inch of the image in the document (defaults to 300) -
	#'   (defaulting to `300`) - (java expects a double)
	#' @param keepUpload keep the uploaded image as a supplementary file in the same
	#'   directory as the google doc - (defaulting to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedImage = function(absoluteFilePath, tagName=deparse(substitute(absoluteFilePath)), dpi=300, keepUpload=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_dpi = self$.api$.toJava$double(dpi);
		tmp_keepUpload = self$.api$.toJava$boolean(keepUpload);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedImage" , tmp_absoluteFilePath, tmp_tagName, tmp_dpi, tmp_keepUpload, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTaggedTable: 
	#' Replace a tag with a table.
	#'   
	#'   Substitutes a unique occurrences of
	#'   {{tag-name}} with a table. The tag should either be in the text of the
	#'   document or as the first entry in 
	#'   the first cell of a table. Once
	#'   inserted the table is tagged using a zero width character
	#'   as the very
	#'   first item in the first cell. This will be removed if `removeTags()`
	#'   is called.
	#'   
	#'   If the tag is missing the table is inserted at the end of
	#'   the document where it can be 
	#'   cut and pasted to the correct place.
	#' @param longFormatTable A dataframe consisting of the table content and
	#'   formatting indexed by row and column. at a minimum this should have
	#'   columns label,row,col, but may also
	#'   include
	#'   rowSpan,colSpan,fillColour, leftBorderWeight,
	#'   rightBorderWeight, topBorderWeight, bottomBorderWeight, alignment
	#'   (START,CENTER,END), valignment (TOP,MIDDLE,BOTTOM), fontName,
	#'   fontFace, fontSize. - (java expects a RDataframe)
	#' @param tagName the tag name - (defaulting to
	#'   `deparse(substitute(longFormatTable))`) - (java expects a String)
	#' @param colWidths A vector including the relative length of each column. This
	#'   can be left out if longFormatTable comes from `as.long_format_table` -
	#'   (defaulting to `attr(longFormatTable,'colWidths')`) - (java expects a RNumericVector)
	#' @param tableWidthInches The final width of the table in inches (defaults to a
	#'   size that fits in A4 page with margins) but you may want to make this
	#'   wider for
	#'     landscape tables - (defaulting to `6.2`) - (java expects a RNumeric)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTaggedTable = function(longFormatTable, tagName=deparse(substitute(longFormatTable)), colWidths=attr(longFormatTable,'colWidths'), tableWidthInches=6.2) {
		# copy parameters
		tmp_longFormatTable = self$.api$.toJava$RDataframe(longFormatTable);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_colWidths = self$.api$.toJava$RNumericVector(colWidths);
		tmp_tableWidthInches = self$.api$.toJava$RNumeric(tableWidthInches);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTaggedTable" , tmp_longFormatTable, tmp_tagName, tmp_colWidths, tmp_tableWidthInches, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' revertTags: 
	#' Revert tagged text and images.
	#'   
	#'   Remove all tagged text and images
	#'   inserted by roogledocs and returns the bare document the tags in
	#'   place. This does not affect figures and tables inserted by index (i.e.
	#'   without tags) 
	#'   This is needed if content is being moved around as cut
	#'   and paste of tagged content unfortunately removes the internal named
	#'   range of the tag.
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	revertTags = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="revertTags" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' removeTags: 
	#' Remove all tags
	#'   
	#'   Finds tags defined in the current document and
	#'   removes them. This 
	#'   cannot be undone, except by rolling back to a
	#'   previous version.
	#' @param confirm - This action must be confirmed by passing `true` as cannot be
	#'   undone. - (defaulting to `(menu(c('Yes','No'), title = 'Are you...`) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	removeTags = function(confirm=(menu(c('Yes','No'), title = 'Are you sure?')==1)) {
		# copy parameters
		tmp_confirm = self$.api$.toJava$boolean(confirm);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="removeTags" , tmp_confirm, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTable: 
	#' Update or insert a formatted table into the document. 
	#'   
	#'   This function
	#'   counts the number of tables from the start of the document.
	#'   Inserting
	#'   tables by index works only if your document does not change much or
	#'   you are creating one from
	#'   scratch. You can overwrite tables using this
	#'   function but if the order of tables has been changed by
	#'   your
	#'   collaborators this will be generally cause probelms. Use of this
	#'   function is generally discouraged and
	#'   we now prefer
	#'   `updateTaggedTable()`.
	#' @param longFormatTable A dataframe consisting of the table content and
	#'   formatting indexed by row and column. at a minimum this should have
	#'   columns label,row,col, but may also
	#'   include
	#'   rowSpan,colSpan,fillColour, leftBorderWeight,
	#'   rightBorderWeight, topBorderWeight, bottomBorderWeight, alignment
	#'   (START,CENTER,END), valignment (TOP,MIDDLE,BOTTOM), fontName,
	#'   fontFace, fontSize. - (java expects a RDataframe)
	#' @param tableIndex what is the table index in the document? This can be left
	#'   out for a new table at the end of the document. - (defaulting to `-1`) - (java expects a int)
	#' @param colWidths A vector including the relative length of each column. This
	#'   can be left out if longFormatTable comes from as.long_format_table -
	#'   (defaulting to `attr(longFormatTable,'colWidths')`) - (java expects a RNumericVector)
	#' @param tableWidthInches The final width of the table in inches (defaults to a
	#'   size that fits in A4 page with margins) - (defaulting to `6.2`) - (java expects a RNumeric)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateTable = function(longFormatTable, tableIndex=-1, colWidths=attr(longFormatTable,'colWidths'), tableWidthInches=6.2) {
		# copy parameters
		tmp_longFormatTable = self$.api$.toJava$RDataframe(longFormatTable);
		tmp_tableIndex = self$.api$.toJava$int(tableIndex);
		tmp_colWidths = self$.api$.toJava$RNumericVector(colWidths);
		tmp_tableWidthInches = self$.api$.toJava$RNumeric(tableWidthInches);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateTable" , tmp_longFormatTable, tmp_tableIndex, tmp_colWidths, tmp_tableWidthInches, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateFigure: 
	#' Update or insert a figure in the document from a locally stored PNG by
	#'   index.
	#'   
	#'   This function counts the number of inline images (i.e. not
	#'   absolutely positioned ones) from the start of the document.
	#'   Inserting
	#'   images by index works only if your document does not change much or
	#'   you are creating one from
	#'   scratch. You can overwrite images using this
	#'   function but if the order of images has been changed by
	#'   your
	#'   collaborators this will generally cause problems. This function
	#'   uploads the image into a temporary file onto your Google Drive, and
	#'   makes it briefly publicly readable. From there inserts it into the
	#'   
	#'   google document. Once this is complete the temporary google drive
	#'   copy of the image is deleted.
	#' @param absoluteFilePath a file path to an png image file (only png is
	#'   supported at this point). - (java expects a String)
	#' @param figureIndex what is the figure index in the document? (This only
	#'   counts inline images - and ignores absolutely positioned ones). leave
	#'   out for a new image at the end of the document. - (defaulting to `-1`) - (java expects a int)
	#' @param dpi the dots per inch of the image in the document (defaults to 300).
	#'   the final size of the image in the doc will be determined by the image
	#'   file dimensions and the dpi. - (defaulting to `300`) - (java expects a double)
	#' @param keepUpload keep the uploaded image as a supplementary file in the same
	#'   directory as the google doc - (defaulting to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateFigure = function(absoluteFilePath, figureIndex=-1, dpi=300, keepUpload=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_figureIndex = self$.api$.toJava$int(figureIndex);
		tmp_dpi = self$.api$.toJava$double(dpi);
		tmp_keepUpload = self$.api$.toJava$boolean(keepUpload);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateFigure" , tmp_absoluteFilePath, tmp_figureIndex, tmp_dpi, tmp_keepUpload, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' saveAsPdf: 
	#' Save the document as a PDF
	#'   
	#'   Saves a snapshot of the current google doc
	#'   with `roogledocs` links removed as a pdf to a local drive. 
	#'   This is
	#'   mainly intended for snapshotting the current state of the document.
	#'   For final export once all
	#'   analysis is complete it may be preferable to
	#'   call `doc$removeTags()` and manually export the output
	#'   but after this
	#'   no further updating is possible.
	#' @param absoluteFilePath - a file path to save the pdf. - (java expects a String)
	#' @param uploadCopy place a copy of the downloaded pdf back onto google drive
	#'   in the same folder as the document
	#'     for example for keeping submitted
	#'   versions of a updated document. This will overwrite files of the same
	#'   name in the 
	#'     google drive directory. - (defaulting to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	saveAsPdf = function(absoluteFilePath, uploadCopy=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_uploadCopy = self$.api$.toJava$boolean(uploadCopy);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="saveAsPdf" , tmp_absoluteFilePath, tmp_uploadCopy, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' makeCopy: 
	#' Make a copy of the current document
	#'   
	#'   This makes a exact copy of the
	#'   document under a new name. This name can already exist as googledocs
	#'   can have multiple 
	#'   files with the same file name but this will
	#'   certainly lead to confusion later. It is up to the user to create
	#'   a
	#'   naming strategy that does not cause issues.
	#' @param newName - The new document name. - (java expects a String)
	#' @return R6 RoogleDocs object: 
	#' a `roogledocs` object pointing to the new document.
	makeCopy = function(newName) {
		# copy parameters
		tmp_newName = self$.api$.toJava$String(newName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="makeCopy" , tmp_newName, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' delete: 
	#' Delete the current document
	#'   
	#'   Deleted documents can still be retrieved
	#'   via the Google Drive website but this is otherwise a 
	#'   final operation.
	#'   After this any operations on this document will fail with a null
	#'   pointer exception.
	#' @param areYouSure - confirm the delete - (defaulting to `utils::askYesNo('Are
	#'   you sure you wan...`) - (java expects a boolean)
	#' @return void: 
	#' 
	delete = function(areYouSure=utils::askYesNo('Are you sure you want to delete this document',FALSE)) {
		# copy parameters
		tmp_areYouSure = self$.api$.toJava$boolean(areYouSure);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="delete" , tmp_areYouSure, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' uploadSupplementaryFiles: 
	#' Upload a file into the same directory as the document.
	#'   
	#'   This allow you
	#'   to load e.g. a supplementary file, or the pdf of an image file or a
	#'   docx/html version of a table
	#'   into google drive into the same directory
	#'   as the document you are editing. This is handy for organising all the
	#'   files
	#'   for a journal submission in one place. Any kind of file can be
	#'   loaded, and the mimetype will be detected. Normal Google Drive rules
	#'   
	#'   for uploads will be triggered at this point. As google drive can have
	#'   multiple files with the same name
	#'   the behaviour if the file already
	#'   exists is slightly complex, with `overwrite` and `duplicate` options.
	#' @param absoluteFilePath - a file path to upload. - (java expects a String)
	#' @param overwrite - if matching file(s) are found in the target, delete them
	#'   before uploading the new one. - (defaulting to `FALSE`) - (java expects a boolean)
	#' @param duplicate - if matching file(s) are found in the target, upload this
	#'   new file anyway, creating duplicate names in the folder. - (defaulting
	#'   to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	uploadSupplementaryFiles = function(absoluteFilePath, overwrite=FALSE, duplicate=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_overwrite = self$.api$.toJava$boolean(overwrite);
		tmp_duplicate = self$.api$.toJava$boolean(duplicate);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="uploadSupplementaryFiles" , tmp_absoluteFilePath, tmp_overwrite, tmp_duplicate, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' appendText: 
	#' Append text to the document with optional paragraph styling. If you
	#'   run text blocks into each other without newlines the whole resulting
	#'   paragraph will be styled. You 
	#'   would normally not want this so it is
	#'   up to you to end paragraphs with a new line character, before changing
	#'   styles.
	#' @param text - a single string with the text to append which may include
	#'   newlines - (java expects a RCharacter)
	#' @param style - one of NORMAL_TEXT, TITLE, SUBTITLE, HEADING_1, ... HEADING_6
	#'   - (defaulting to `'NORMAL_TEXT'`) - (java expects a RCharacter)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	appendText = function(text, style='NORMAL_TEXT') {
		# copy parameters
		tmp_text = self$.api$.toJava$RCharacter(text);
		tmp_style = self$.api$.toJava$RCharacter(style);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="appendText" , tmp_text, tmp_style, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' appendFormattedParagraph: 
	#' Append a new paragraph, with text from the 'label' column with
	#'   optional formating in the other columns.
	#' @param formattedTextDf - a data frame containing the columns label, and
	#'   optionally: link (as a URL), fontName, fontFace, fontSize. - (java expects a RDataframe)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	appendFormattedParagraph = function(formattedTextDf) {
		# copy parameters
		tmp_formattedTextDf = self$.api$.toJava$RDataframe(formattedTextDf);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="appendFormattedParagraph" , tmp_formattedTextDf, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateCitations: 
	#' Update citation tags in the document. 
	#'   
	#'   A citation tag is like this
	#'   `{{cite:challen2020;danon2021}}`. The ids are matched against the
	#'   provided bibtex, and
	#'   the tags are replaced with an appropriate
	#'   citation string. The bibliography itself is added to a specific slide
	#'   for 
	#'   references which can be decided with the `{{references}}` tag.
	#'   
	#'   
	#'   If references do not already exist and there if no `{{references}}`
	#'   tag the
	#'   references will be added to the end of the document. Where it
	#'   can be cut and
	#'   pasted to the right place. N.B. Do not split up the
	#'   references when you move them.
	#' @param bibTexPath - the full file path to the file containing the bibtex - (java expects a RCharacter)
	#' @param citationStyle - the CSL specification - (defaulting to
	#'   `'ieee-with-url'`) - (java expects a RCharacter)
	#' @return R6 RoogleDocs object: 
	#' itself - a fluent method
	updateCitations = function(bibTexPath, citationStyle='ieee-with-url') {
		# copy parameters
		tmp_bibTexPath = self$.api$.toJava$RCharacter(bibTexPath);
		tmp_citationStyle = self$.api$.toJava$RCharacter(citationStyle);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleDocs;", method="updateCitations" , tmp_bibTexPath, tmp_citationStyle, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleDocs$new(
				self$.api$.fromJava$RoogleDocs(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	
	#' @description The output of toString() of this RoogleDocs
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this RoogleDocs
	#' @param object The R6 instance to test for equality to this RoogleDocs  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/roogledocs/RoogleDocs")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
