# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# R Wrapper For Googledocs Java Library
#' R6 Bindings for Java RoogleSlides
#'
#' @description
#' Programmatically substitute images, data and tables into a google presentation. 
#' 
#' This is a class of the roogledocs generated R library.
#' 
#' Version: 0.4.0
#' 
#' Generated: 2024-04-05T16:34:41.914748237
#'
#' @details
	#' The purpose being to support google slides as a
	#'   platform for
	#'   interactive development and documentation of data analysis in R. The
	#'   workflow supported is a parallel documentation and analysis
	#'   where a
	#'   team of people are working collaboratively on documentation, whilst at
	#'   the same time analysis
	#'   is being performed and results updated
	#'   repeatedly as a result of new data. In this environment
	#'   updating
	#'   numeric results, tabular data and figures in word documents
	#'   manually becomes annoying. With roogledocs
	#'   you can automate this a bit
	#'   like a RMarkdown document, but with the added benefit that the
	#'   content
	#'   can be updated independently of the analysis, by the wider
	#'   team.
#' @export
RoogleSlides = R6::R6Class("RoogleSlides", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new RoogleSlides this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new RoogleSlides object.
	#' @examples
	#' \dontrun{
	#' J = roogledocs::JavaApi$get()
	#' # This constructor must be called via the JavaApi where an appropriate set of parameters must be provided.
	#' instance = J$RoogleSlides$new(tokenDirectory=.tokenDirectory(), disabled=getOption('roogledocs.disabled',FALSE))
	#' }	
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description 
	#' enable: 
	#' Enables roogledocs method calls for this document. 
	#'   
	#'   It is likely one
	#'   of `withDocument()`, `findOrCreateDocument()` or
	#'   `findOrCloneTemplate()` methods will be needed to specify the
	#'   document.
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	enable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="enable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' disable: 
	#' Disables roogledocs temporarily for this document. 
	#'   
	#'   While disabled
	#'   all calls to roogledocs will silently abort.
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	disable = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="disable" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' getName: 
	#' Return the name of the presentation
	#' @param suffix an additional suffix to add to the name - (defaulting to `''`) - (java expects a String)
	#' @return String: 
	#' 
	getName = function(suffix='') {
		# copy parameters
		tmp_suffix = self$.api$.toJava$String(suffix);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="getName" , tmp_suffix, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$String(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' tagsDefined: 
	#' List all tags
	#'   
	#'   Finds tags defined in the current document
	#' @return RDataframe: 
	#' a dataframe containing tag and count columns
	tagsDefined = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="tagsDefined" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' updateTaggedText: 
	#' Replace tags for text
	#'   
	#'   Substitutes all occurrences of {{tag-name}}
	#'   with the text parameter. If the
	#'   tag is not found then a new slide is
	#'   inserted at the end in a section titled "Unmatched tags:". 
	#'   From there
	#'   they can be cut and pasted into the right place.
	#' @param text the value to replace the tag with (e.g. a result from analysis)
	#'   (cannot be empty) - (java expects a String)
	#' @param tagName the tag name - (defaulting to `deparse(substitute(text))`) - (java expects a String)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	updateTaggedText = function(text, tagName=deparse(substitute(text))) {
		# copy parameters
		tmp_text = self$.api$.toJava$String(text);
		tmp_tagName = self$.api$.toJava$String(tagName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="updateTaggedText" , tmp_text, tmp_tagName, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTaggedImage: 
	#' Replace a tag with an image.
	#'   
	#'   Substitutes all occurrences of
	#'   {{tag-name}} with an image from the local storage. 
	#'   
	#'   The image is
	#'   uploaded to your google drive as a temporary file, and made publicly
	#'   readable. From there it is inserted into the 
	#'   google slides, and once
	#'   completed the temporary file deleted from your google drive, unless
	#'   `keepUpload` is true. Insertion
	#'   is done in the dimensions of the
	#'   containing box of the image if it already exists or
	#'   a default slide
	#'   body box if not. 
	#'   
	#'   If the tag is not found in the document a new slide
	#'   will be created at the end of the presentation with the image
	#'   and an
	#'   uninformative title which can be changed.
	#' @param absoluteFilePath a file path to an png image file. - (java expects a String)
	#' @param tagName the tag name - (defaulting to
	#'   `deparse(substitute(absoluteFilePath))`) - (java expects a String)
	#' @param keepUpload keep the uploaded image as a supplementary file in the same
	#'   directory as the google doc. N.B. the result will be publicly
	#'   readable. - (defaulting to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	updateTaggedImage = function(absoluteFilePath, tagName=deparse(substitute(absoluteFilePath)), keepUpload=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_keepUpload = self$.api$.toJava$boolean(keepUpload);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="updateTaggedImage" , tmp_absoluteFilePath, tmp_tagName, tmp_keepUpload, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateTaggedTable: 
	#' Replace a tag with a table.
	#'   
	#'   Substitutes a unique occurrence of
	#'   {{tag-name}} with a table. The tag must either be in a text box shape
	#'   or as the first entry in 
	#'   a table. Once inserted the table is tagged
	#'   using a zero width character
	#'   as the very first item in the first cell.
	#'   This will be removed if `removeTags()` is called.
	#'   
	#'   If the tag is not
	#'   found in the document a new slide will be created at the end with the
	#'   table.
	#' @param longFormatTable A dataframe consisting of the table content and
	#'   formatting indexed by row and column. at a minimum this should have
	#'   columns label,row,col, but may also
	#'   include
	#'   rowSpan,colSpan,fillColour, leftBorderWeight,
	#'   rightBorderWeight, topBorderWeight, bottomBorderWeight, alignment
	#'   (START,CENTER,END), valignment (TOP,MIDDLE,BOTTOM), fontName,
	#'   fontFace, fontSize. - (java expects a RDataframe)
	#' @param tagName the tag name - (defaulting to
	#'   `deparse(substitute(longFormatTable))`) - (java expects a String)
	#' @param colWidths A vector including the relative length of each column. This
	#'   can be left out if longFormatTable comes from as.long_format_table -
	#'   (defaulting to `attr(longFormatTable,'colWidths')`) - (java expects a RNumericVector)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	updateTaggedTable = function(longFormatTable, tagName=deparse(substitute(longFormatTable)), colWidths=attr(longFormatTable,'colWidths')) {
		# copy parameters
		tmp_longFormatTable = self$.api$.toJava$RDataframe(longFormatTable);
		tmp_tagName = self$.api$.toJava$String(tagName);
		tmp_colWidths = self$.api$.toJava$RNumericVector(colWidths);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="updateTaggedTable" , tmp_longFormatTable, tmp_tagName, tmp_colWidths, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' removeTags: 
	#' Remove all tags
	#'   
	#'   Finds tags defined in the current document and
	#'   removes them. This 
	#'   cannot be undone, except by rolling back to a
	#'   previous version.
	#' @param confirm - This action must be confirmed by passing `true` as cannot be
	#'   undone. - (defaulting to `(menu(c('Yes','No'), title = 'Are you...`) - (java expects a boolean)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	removeTags = function(confirm=(menu(c('Yes','No'), title = 'Are you sure?')==1)) {
		# copy parameters
		tmp_confirm = self$.api$.toJava$boolean(confirm);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="removeTags" , tmp_confirm, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' saveAsPdf: 
	#' Save the document as a PDF
	#'   
	#'   Saves a snapshot of the current google
	#'   slides with `roogledocs` links removed as a pdf to a local drive.
	#'   
	#'   This is mainly intended for snap-shotting the current state of the
	#'   document. For final export once all
	#'   analysis is complete it may be
	#'   preferable to call `doc$removeTags()` and manually export the
	#'   output
	#'   but after this no further updating is possible.
	#' @param absoluteFilePath - a file path to save the pdf. - (java expects a String)
	#' @param uploadCopy place a copy of the downloaded pdf back onto google drive
	#'   in the same folder as the document
	#'     for example for keeping submitted
	#'   versions of a updated document. This will overwrite files of the same
	#'   name in the 
	#'     google drive directory. - (defaulting to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	saveAsPdf = function(absoluteFilePath, uploadCopy=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_uploadCopy = self$.api$.toJava$boolean(uploadCopy);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="saveAsPdf" , tmp_absoluteFilePath, tmp_uploadCopy, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' makeCopy: 
	#' Make a copy of the current document
	#'   
	#'   This makes a exact copy of the
	#'   document under a new name. This name can already exist as googledocs
	#'   can have multiple 
	#'   files with the same file name but this will
	#'   certainly lead to confusion later. It is up to the user to create
	#'   a
	#'   naming strategy that does not cause issues.
	#' @param newName - The new document name. - (java expects a String)
	#' @return R6 RoogleSlides object: 
	#' a `roogledocs` object pointing to the new document.
	makeCopy = function(newName) {
		# copy parameters
		tmp_newName = self$.api$.toJava$String(newName);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="makeCopy" , tmp_newName, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' delete: 
	#' Delete the current presentation
	#'   
	#'   Deleted presentations can still be
	#'   retrieved via the Google Drive website but this is otherwise a 
	#'   final
	#'   operation. After this any operations on this presentation will fail
	#'   with a null pointer exception.
	#' @param areYouSure - confirm the delete - (defaulting to `utils::askYesNo('Are
	#'   you sure you wan...`) - (java expects a boolean)
	#' @return void: 
	#' 
	delete = function(areYouSure=utils::askYesNo('Are you sure you want to delete this presentation',FALSE)) {
		# copy parameters
		tmp_areYouSure = self$.api$.toJava$boolean(areYouSure);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "V", method="delete" , tmp_areYouSure, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$void(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' uploadSupplementaryFiles: 
	#' Upload a file into the same directory as the document.
	#'   
	#'   This allow you
	#'   to load e.g. a supplementary file, or the pdf of an image file or a
	#'   docx/html version of a table
	#'   into google drive into the same directory
	#'   as the slides you are editing. This is handy for organising all the
	#'   files
	#'   for a journal submission in one place. Any kind of file can be
	#'   loaded, and the mimetype will be detected. Normal Google Drive rules
	#'   
	#'   for uploads will be triggered at this point. As google drive can have
	#'   multiple files with the same name
	#'   the behaviour if the file already
	#'   exists is slightly complex, with `overwrite` and `duplicate` options.
	#' @param absoluteFilePath - a file path to upload. - (java expects a String)
	#' @param overwrite - if matching file(s) are found in the target, delete them
	#'   before uploading the new one. - (defaulting to `FALSE`) - (java expects a boolean)
	#' @param duplicate - if matching file(s) are found in the target, upload this
	#'   new file anyway, creating duplicate names in the folder. - (defaulting
	#'   to `FALSE`) - (java expects a boolean)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	uploadSupplementaryFiles = function(absoluteFilePath, overwrite=FALSE, duplicate=FALSE) {
		# copy parameters
		tmp_absoluteFilePath = self$.api$.toJava$String(absoluteFilePath);
		tmp_overwrite = self$.api$.toJava$boolean(overwrite);
		tmp_duplicate = self$.api$.toJava$boolean(duplicate);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="uploadSupplementaryFiles" , tmp_absoluteFilePath, tmp_overwrite, tmp_duplicate, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' appendFormattedSlide: 
	#' Append a new "TITLE_AND_BODY" slide, with formatted text from the
	#'   'label' column with optional formating in the other columns.
	#' @param title - A plain text title - (java expects a String)
	#' @param formattedTextDf - a data frame containing the columns label, and
	#'   optionally: link (as a URL), fontName, fontFace, fontSize. - (java expects a RDataframe)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	appendFormattedSlide = function(title, formattedTextDf) {
		# copy parameters
		tmp_title = self$.api$.toJava$String(title);
		tmp_formattedTextDf = self$.api$.toJava$RDataframe(formattedTextDf);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="appendFormattedSlide" , tmp_title, tmp_formattedTextDf, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' slideDimensions: 
	#' The default dimensions of the body of a new slide.
	#'   
	#'   A new slide will
	#'   be created using a default layout which is usually the 
	#'   slide layout
	#'   with the biggest text box on it. This can be set manually with
	#'   the
	#'   `setDefaultLayout()` function.  
	#'   
	#'   The body is the largest text box
	#'   on the slide. This is the place that images or 
	#'   tables will be placed
	#'   by default. If you want to fit in with the theme then 
	#'   images will
	#'   need to be to be sized to these dimensions to fill the slide.
	#' @return RNamedList: 
	#' a named list with width and height in inches, and the name of the
	#'   layout being
	#'     used as the default.
	slideDimensions = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RNamedList;", method="slideDimensions" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RNamedList(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' slideLayouts: 
	#' The layouts available in the slides templates
	#' @return RCharacterVector: 
	#' a list of available slide layouts
	slideLayouts = function() {
		# copy parameters
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RCharacterVector;", method="slideLayouts" , check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# convert java object back to R
		out = self$.api$.fromJava$RCharacterVector(tmp_out);
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	#' @description 
	#' setDefaultLayout: 
	#' Set the default layout
	#'   
	#'   The default layout for the slide is used when
	#'   inserting new slides at
	#'   the end of the document for images. A default
	#'   layout will have 2 text
	#'   boxes, one for the title and one for the
	#'   content. The second text box will
	#'   be large. The layouts in a
	#'   presentation can be listed with `slideLayouts()` or
	#'   seen on the google
	#'   slides `Apply Layout...` menu option.
	#' @param layout a string representing the layout - (java expects a RCharacter)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	setDefaultLayout = function(layout) {
		# copy parameters
		tmp_layout = self$.api$.toJava$RCharacter(layout);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="setDefaultLayout" , tmp_layout, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	#' @description 
	#' updateCitations: 
	#' Update citation tags in the document. 
	#'   
	#'   A citation tag is like this
	#'   `{{cite:challen2020;danon2021}}`. The ids are matched against the
	#'   provided bibtex, and
	#'   the tags are replaced with an appropriate
	#'   citation string. The bibliography itself is added to a specific slide
	#'   for 
	#'   references which can be decided with the `{{references}}` tag.
	#'   
	#'   
	#'   If references do not already exist and there if no `{{references}}`
	#'   tag a new slide 
	#'   will be created at the end of the presentation.
	#' @param bibTexPath - the full file path to the file containing the bibtex - (java expects a RCharacter)
	#' @param citationStyle - the CSL specification - (defaulting to `'ieee'`) - (java expects a RCharacter)
	#' @return R6 RoogleSlides object: 
	#' itself - a fluent method
	updateCitations = function(bibTexPath, citationStyle='ieee') {
		# copy parameters
		tmp_bibTexPath = self$.api$.toJava$RCharacter(bibTexPath);
		tmp_citationStyle = self$.api$.toJava$RCharacter(citationStyle);
		# execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/roogledocs/RoogleSlides;", method="updateCitations" , tmp_bibTexPath, tmp_citationStyle, check=FALSE);
		self$.api$printMessages()
		# check for exceptions and rethrow them
		.jcheck()
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = RoogleSlides$new(
				self$.api$.fromJava$RoogleSlides(tmp_out),
				self$.api
			);
			return(out);
		}
	},
	
	#' @description The output of toString() of this RoogleSlides
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this RoogleSlides
	#' @param object The R6 instance to test for equality to this RoogleSlides  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/roogledocs/RoogleSlides")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
