
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
## uncomment this to run on a fixed schedule
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 12 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ${{ matrix.config.os }}

    continue-on-error: false

    name: ${{ matrix.config.os }} R:(${{ matrix.config.r }} Java:${{ matrix.config.java }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: '4.1.0', java: 11, distribution: zulu}
          - {os: macOS-11, r: '4.1.0', java: 11, distribution: zulu}
          - {os: windows-2022, r: '4.1.0', java: 11, distribution: zulu}
          - {os: ubuntu-20.04, r: '3.6.1', java: 8, distribution: zulu}
          - {os: ubuntu-20.04, r: '4.2.0', java: 17, distribution: zulu}
          - {os: ubuntu-20.04, r: 'devel', java: 17, distribution: zulu, http-user-agent: 'release'}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    if: "!contains(github.event.head_commit.message, 'revdepcheck run - No changes to commit')"

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.config.java }}
          distribution: ${{ matrix.config.distribution }}
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Info
        run: "bash -c 'java -version && which java && echo $PATH && echo $JAVA_HOME'"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: any::rcmdcheck
          needs: check
      
      - name: Setup R Java support
        if: runner.os != 'Windows'
        run: "echo export PATH=$PATH > reconf.sh; echo export JAVA_HOME=$JAVA_HOME >> reconf.sh; echo R CMD javareconf >> reconf.sh; sudo bash reconf.sh"

      - name: Set up secrets dir
        run: "bash -c 'mkdir ~/.roogledocs-test'"

      # Decode the secret to ~/.roogledocs-test
      - name: Decode secrets
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'StoredCredential'
          fileDir: '~/.roogledocs-test'
          encodedString: ${{ secrets.STOREDCREDENTIAL }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--no-multiarch", "--as-cran")'
          upload-snapshots: true

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-${{ matrix.config.java }}-results
          path: check
